create signup ui
nanarboursal/Angle pull request #6
Opened 2021-11-11 02:33 UTC by jj904

2021-11-11 20:50 UTC, nanarboursal approved these changes
sign up functionality remains in tact

2021-11-13 22:47 UTC, Aneesh-Pothuru commented
Hey Grace,
This is fine to merge, it works on my machine. Please remove the comments if you can. 
Thanks,
Aneesh

2021-11-13 22:54 UTC, Aneesh-Pothuru requested changes
Hey Grace,
I actually ran this commit in parallel to Edgar's changes. This is actually breaking the user interface from the different styling logic you both used. Please go over this with each other and submit changes.

2021-11-13 22:54 UTC, Aneesh-Pothuru commented on angle-ui/src/Pages/SignUp/signup.css
> +    */
Please remove comments

2021-11-13 22:54 UTC, Aneesh-Pothuru commented on angle-ui/src/Pages/SignUp/signup.css
> +    */
Please remove comments

2021-11-18 03:15 UTC, merged